language: node_js
node_js:
  - 'lts/*'

cache:
  directories:
    - node_modules

branches:
  only:
    - main
    - staging

script:
  - npm install
  - npm run build --prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the Travis CI settings
  local_dir: dist/CityPulse
  on:
    branch: Deploy